import attack_map from "./attack_map";
let TableData = [
  {
    key: "1",
    reconnaissance: "Active Scanning",
    resource: "Acquire Access",
    initial: "Content Injection",
    execution: "Cloud Administration Command",
    persistence: "Account Manipulation",
    privilege: "Abuse Elevation Control Mechanism",
    defense: "Abuse Elevation Control Mechanism",
    credential: "Adversary-in-the-Middle",
    discovery: "Account Discovery",
    lateral: "Exploitation of Remote Services",
    collection: "Adversary-in-the-Middle",
    command: "Application Layer Protocol",
    exfiltration: "Automated Exfiletration",
    impact: "Account Access Removal",
  },
  {
    key: "2",
    reconnaissance: "Gather Victim Host Information",
    resource: "Acquire Infrastructure",
    initial: "Derive-by-Compromise",
    execution: "Command and Scripting Interpreter",
    persistence: "BITS Jobs",
    privilege: "Access Token Manipulation",
    defense: "Access Token Manipulation",
    credential: "Brute Force",
    discovery: "Application Window Discovery",
    lateral: "Internal Spearphishing",
    collection: "Archive Collected Data",
    command: "Communication Through Removable Media",
    exfiltration: "Data Transfer Size Limits",
    impact: "Data Destruction",
  },
  {
    key: "3",
    reconnaissance: "Gather Victim Identity Information",
    resource: "Compromise Accounts",
    initial: "Exploit Public-Facing Application",
    execution: "Container Administration Command",
    persistence: "Boot or Logon Autostart Execution",
    privilege: "Account Manipulation",
    defense: "BITS Jobs",
    credential: "Credentials from Password Stores",
    discovery: "Browser Information Discovery",
    lateral: "Lateral Tool Transfer",
    collection: "Audio Capture",
    command: "Content Injection",
    exfiltration: "Exfiletration Over Alternative Protocol",
    impact: "Data Encrypted foe Impact",
  },
  {
    key: "4",
    reconnaissance: "Gather Victim Network Information",
    resource: "Compromise Infrastructure",
    initial: "External Remote Services",
    execution: "Deploy Container",
    persistence: "Boot or Logon Initialization Scripts",
    privilege: "Boot or Logon Autostart Execution ",
    defense: "Abuse Elevation Control Mechanism",
    credential: "Adversary-in-the-Middle",
    discovery: "Account Discovery",
    lateral: "Exploitation of Remote Services",
    collection: "Adversary-in-the-Middle",
    command: "Data Encoding",
    exfiltration: "Exfiletration Over C2 Channel",
    impact: "Data Manipulation",
  },
  {
    key: "5",
    reconnaissance: "Gather Victim Org Information",
    resource: "Develop Capabilities",
    initial: "Hardware Additions",
    execution: "Exploitation for Client Execution",
    persistence: "Browser Extensions",
    privilege: "Boot or Logon Initialization Scripts",
    defense: "Debugger Evasion",
    credential: "Forced Authentication",
    discovery: "Cloud Service Dashboard",
    lateral: "Remote Services",
    collection: "Browser Session Hijacking",
    command: "Data Obfuscation",
    exfiltration: "Exfiltration Over Other Network Medium",
    impact: "Defacement",
  },
  {
    key: "6",
    reconnaissance: "Phishing for Information",
    resource: "Establish Accounts",
    initial: "Phishing",
    execution: "Inter-Process Communication",
    persistence: "Compromise Host Software Binary",
    privilege: "Create or Modify System Process ",
    defense: "Deobfuscate/Decode Files or Information",
    credential: "Forge Web Credentials",
    discovery: "Cloud Service Discovery",
    lateral: "Replication Through Removable Media",
    collection: "Clipboard Data",
    command: "Dynamic Resolution",
    exfiltration: "Exfiltration Over Physical Medium",
    impact: "Disk Wipe",
  },
  {
    key: "7",
    reconnaissance: "Search Closed Sources",
    resource: "Obtain Capabilities",
    initial: "Replication Through Removable Media",
    execution: "Native API",
    persistence: "Create Account",
    privilege: "Domain or Tenant Policy Modification",
    defense: "Deploy Container",
    credential: "Input Capture",
    discovery: "Cloud Storage Object Discovery",
    lateral: "Software Deployment Tools",
    collection: "Data from Cloud Storage",
    command: "Encrypted Channel",
    exfiltration: "Exfiltration Over Web Service",
    impact: "End Point Denial of Service",
  },
  {
    key: "8",
    reconnaissance: "Search Open Technical Databases",
    resource: "Stage Capabilities",
    initial: "Supply Chain Compromise",
    execution: "Scheduled Task / Job",
    persistence: "Create or Modify System Process",
    privilege: "Escape to Host",
    defense: "Direct Volume Access",
    credential: "Modify Authentication Process",
    discovery: "Container and Resource Discovery",
    lateral: "Taint Shared Content",
    collection: "Data from Configuration Repository",
    command: "Fallback Channels",
    exfiltration: "Scheduled Transfer",
    impact: "Financial Theft",
  },
  {
    key: "9",
    reconnaissance: "Search Open Websites/Domains",
    resource: "",
    initial: "Trusted Relationship",
    execution: "Serverless Execution",
    persistence: "Event Triggered Execution",
    privilege: "Event Triggered Execution",
    defense: "Domain or Tenant Policy Modification",
    credential: "Multi-Factor Authentication Interception",
    discovery: "Debugger Evasion",
    lateral: "Use Alternate Authentication Material",
    collection: "Data from Information Repositories",
    command: "Hide Infrastructure",
    exfiltration: "Transfer Data to Cloud Account",
    impact: "Firmware Corruption",
  },
  {
    key: "10",
    reconnaissance: "Search Victim-Owned Websites",
    resource: "",
    initial: "Valid Account",
    execution: "Shared Modules",
    persistence: "External Remote Services",
    privilege: "Exploitation for Privilege Escalation",
    defense: "Execution Guardrails",
    credential: "Multi-Factor Authentication Request Generation",
    discovery: "Device Driver Discovery",
    lateral: "",
    collection: "Data from Local System",
    command: "Ingress Tool Transfer",
    exfiltration: "",
    impact: "Inhibit System Recovery",
  },

  {
    key: "11",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "Software Development Tools",
    persistence: "Highjack Execution Flow",
    privilege: "Hijack Execution Flow",
    defense: "Exploitation for Defense Evasion",
    credential: "Network Sniffing",
    discovery: "Device Driver Discovery",
    lateral: "",
    collection: "Data from Network Shared Drive",
    command: "Multi-Stage Channels",
    exfiltration: "",
    impact: "Network Denial of Service",
  },
  {
    key: "12",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "System Services",
    persistence: "Implant Internal Image",
    privilege: "Process Injection",
    defense: "File and Directory Permissions Modification",
    credential: "OS Credential Dumping",
    discovery: "Device Driver Discovery",
    lateral: "",
    collection: "Data from Removable Media",
    command: "Non-Application Layer Protocol",
    exfiltration: "",
    impact: "Resource Hijacking",
  },
  {
    key: "13",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "User Execution",
    persistence: "Modify Authentication Process",
    privilege: "Scheduled Task/Job",
    defense: "Hide Artifacts",
    credential: "Steal Application Access Token",
    discovery: "Device Driver Discovery",
    lateral: "",
    collection: "Data Staged",
    command: "Non-Standard Port",
    exfiltration: "",
    impact: "Service Stop",
  },
  {
    key: "14",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "Windows Management Instruction",
    persistence: "Office Application Startup",
    privilege: "Valid Accounts",
    defense: "Hijack Execution Flow",
    credential: "Steal or Forge Authentication Certificates",
    discovery: "Device Driver Discovery",
    lateral: "",
    collection: "Email Collection",
    command: "Protocol Tunneling",
    exfiltration: "",
    impact: "System Shutdown/Reboot",
  },
  {
    key: "15",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "",
    persistence: "Power Settings",
    privilege: "",
    defense: "Impair Defenses",
    credential: "Steal or Forge Kerberos Ticket",
    discovery: "Device Driver Discovery",
    lateral: "",
    collection: "Input Capture",
    command: "Proxy",
    exfiltration: "",
    impact: "",
  },
  {
    key: "16",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "Shared Modules",
    persistence: "Per-OS-Boot",
    privilege: "",
    defense: "Impersonation",
    credential: "Steal Web Session Cookie",
    discovery: "Device Driver Discovery",
    lateral: "",
    collection: "Screen Capture",
    command: "Remote Access Software",
    exfiltration: "",
    impact: "",
  },
  {
    key: "17",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "Shared Modules",
    persistence: "Scheduled Task/Job",
    privilege: "",
    defense: "Indicator Removal",
    credential: "Unsecured Credentials",
    discovery: "Network Sniffing",
    lateral: "",
    collection: "Video Capture",
    command: "Traffic Signaling",
    exfiltration: "",
    impact: "",
  },
  {
    key: "18",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "Shared Modules",
    persistence: "Server Software Component",
    privilege: "",
    defense: "Indirect Command Execution",
    credential: "",
    discovery: "Password Policy Discovery",
    lateral: "",
    collection: "",
    command: "Web Service",
    exfiltration: "",
    impact: "",
  },
  {
    key: "19",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "Shared Modules",
    persistence: "Traffic Signaling",
    privilege: "",
    defense: "Masquerading",
    credential: "",
    discovery: "Peripheral Device",
    lateral: "",
    collection: "",
    command: "",
    exfiltration: "",
    impact: "",
  },
  {
    key: "20",
    reconnaissance: "",
    resource: "",
    initial: "",
    execution: "Shared Modules",
    persistence: "Valid Accounts",
    privilege: "",
    defense: "Modify Authentication Process",
    credential: "",
    discovery: "",
    lateral: "",
    collection: "",
    command: "",
    exfiltration: "",
    impact: "",
  },
];
// Create a lookup dictionary for quick access to MITRE IDs
const attackLookup = attack_map.reduce((acc, item) => {
  acc[item.attack] = item.mitreid;
  return acc;
}, {});

// Function to transform the TableData
const transformTableData = (tableData) => {
  return tableData.map((entry) => {
    let newEntry = { key: entry.key };

    Object.keys(entry).forEach((field) => {
      if (field !== "key") {
        newEntry[field] = {
          name: entry[field],
          attack_id: attackLookup[entry[field]] || "Unknown", // Assign "Unknown" if not found
        };
      }
    });

    return newEntry;
  });
};
TableData = transformTableData(TableData);
console.log("Table Data **************************************", TableData);
export default TableData;
