import attack_map from "./attack_map";
let TableData = [
  {
    key: "1",
    reconnaissance: "Active Scanning",
    resource: "Acquire Access",
    initial: "Content Injection",
    execution: "Cloud Administration Command",
    persistence: "Account Manipulation",
    privilege: "Abuse Elevation Control Mechanism",
    defense: "Abuse Elevation Control Mechanism",
    credential: "Adversary-in-the-Middle",
    discovery: "Account Discovery",
    lateral: "Exploitation of Remote Services",
    collection: "Adversary-in-the-Middle",
    command: "Application Layer Protocol",
    exfiltration: "Automated Exfiletration",
    impact: "Account Access Removal",
  },
  {
    key: "2",
    reconnaissance: "Gather Victim Host Information",
    resource: "Acquire Infrastructure",
    initial: "Derive-by-Compromise",
    execution: "Command and Scripting Interpreter",
    persistence: "BITS Jobs",
    privilege: "Access Token Manipulation",
    defense: "Access Token Manipulation",
    credential: "Brute Force",
    discovery: "Application Window Discovery",
    lateral: "Internal Spearphishing",
    collection: "Archive Collected Data",
    command: "Communication Through Removable Media",
    exfiltration: "Data Transfer Size Limits",
    impact: "Data Destruction",
  },
  {
    key: "3",
    reconnaissance: "Gather Victim Identity Information",
    resource: "Compromise Accounts",
    initial: "Exploit Public-Facing Application",
    execution: "Container Administration Command",
    persistence: "Boot or Logon Autostart Execution",
    privilege: "Account Manipulation",
    defense: "BITS Jobs",
    credential: "Credentials from Password Stores",
    discovery: "Browser Information Discovery",
    lateral: "Lateral Tool Transfer",
    collection: "Audio Capture",
    command: "Content Injection",
    exfiltration: "Exfiletration Over Alternative Protocol",
    impact: "Data Encrypted foe Impact",
  },
  {
    key: "4",
    reconnaissance: "Gather Victim Network Information",
    resource: "Compromise Infrastructure",
    initial: "External Remote Services",
    execution: "Deploy Container",
    persistence: "Boot or Logon Initialization Scripts",
    privilege: "Boot or Logon Autostart Execution ",
    defense: "Abuse Elevation Control Mechanism",
    credential: "Adversary-in-the-Middle",
    discovery: "Account Discovery",
    lateral: "Exploitation of Remote Services",
    collection: "Adversary-in-the-Middle",
    command: "Data Encoding",
    exfiltration: "Exfiletration Over C2 Channel",
    impact: "Data Manipulation",
  },
  {
    key: "5",
    reconnaissance: "Gather Victim Org Information",
    resource: "Develop Capabilities",
    initial: "Hardware Additions",
    execution: "Exploitation for Client Execution",
    persistence: "Browser Extensions",
    privilege: "Boot or Logon Initialization Scripts",
    defense: "Debugger Evasion",
    credential: "Forced Authentication",
    discovery: "Cloud Service Dashboard",
    lateral: "Remote Services",
    collection: "Browser Session Hijacking",
    command: "Data Obfuscation",
    exfiltration: "Exfiltration Over Other Network Medium",
    impact: "Defacement",
  },
  {
    key: "6",
    reconnaissance: "Phishing for Information",
    resource: "Establish Accounts",
    initial: "Phishing",
    execution: "Inter-Process Communication",
    persistence: "Compromise Host Software Binary",
    privilege: "Create or Modify System Process ",
    defense: "Deobfuscate/Decode Files or Information",
    credential: "Forge Web Credentials",
    discovery: "Cloud Service Discovery",
    lateral: "Replication Through Removable Media",
    collection: "Clipboard Data",
    command: "Dynamic Resolution",
    exfiltration: "Exfiltration Over Physical Medium",
    impact: "Disk Wipe",
  },
  {
    key: "7",
    reconnaissance: "Search Closed Sources",
    resource: "Obtain Capabilities",
    initial: "Replication Through Removable Media",
    execution: "Native API",
    persistence: "Create Account",
    privilege: "Domain or Tenant Policy Modification",
    defense: "Deploy Container",
    credential: "Input Capture",
    discovery: "Cloud Storage Object Discovery",
    lateral: "Software Deployment Tools",
    collection: "Data from Cloud Storage",
    command: "Encrypted Channel",
    exfiltration: "Exfiltration Over Web Service",
    impact: "End Point Denial of Service",
  },
  {
    key: "8",
    reconnaissance: "Search Open Technical Databases",
    resource: "Stage Capabilities",
    initial: "Supply Chain Compromise",
    execution: "Scheduled Task / Job",
    persistence: "Create or Modify System Process",
    privilege: "Escape to Host",
    defense: "Direct Volume Access",
    credential: "Modify Authentication Process",
    discovery: "Container and Resource Discovery",
    lateral: "Taint Shared Content",
    collection: "Data from Configuration Repository",
    command: "Fallback Channels",
    exfiltration: "Scheduled Transfer",
    impact: "Financial Theft",
  },
  {
    key: "9",
    reconnaissance: "Search Open Websites/Domains",
    resource: "",
    initial: "Trusted Relationship",
    execution: "Serverless Execution",
    persistence: "Event Triggered Execution",
    privilege: "Event Triggered Execution",
    defense: "Domain or Tenant Policy Modification",
    credential: "Multi-Factor Authentication Interception",
    discovery: "Debugger Evasion",
    lateral: "Use Alternate Authentication Material",
    collection: "Data from Information Repositories",
    command: "Hide Infrastructure",
    exfiltration: "Transfer Data to Cloud Account",
    impact: "Firmware Corruption",
  },
  {
    key: "10",
    reconnaissance: "Search Victim-Owned Websites",
    resource: "",
    initial: "Valid Account",
    execution: "Shared Modules",
    persistence: "External Remote Services",
    privilege: "Exploitation for Privilege Escalation",
    defense: "Execution Guardrails",
    credential: "Multi-Factor Authentication Request Generation",
    discovery: "Device Driver Discovery",
    lateral: "",
    collection: "Data from Local System",
    command: "Ingress Tool Transfer",
    exfiltration: "",
    impact: "Inhibit System Recovery",
  },
];
// Create a lookup dictionary for quick access to MITRE IDs
const attackLookup = attack_map.reduce((acc, item) => {
  acc[item.attack] = item.mitreid;
  return acc;
}, {});

// Function to transform the TableData
const transformTableData = (tableData) => {
  return tableData.map((entry) => {
    let newEntry = { key: entry.key };

    Object.keys(entry).forEach((field) => {
      if (field !== "key") {
        newEntry[field] = {
          name: entry[field],
          attack_id: attackLookup[entry[field]] || "Unknown", // Assign "Unknown" if not found
        };
      }
    });

    return newEntry;
  });
};
TableData = transformTableData(TableData);
console.log("Table Data **************************************", TableData)
export default TableData;
