INCIDENT_MAPPING = {
    9: "OPEN_PORT_SCANS",
    48: "DDOS_ATTACK_DETECTED",
    51: "PHISHING_EMAIL_DETECTED",
    52: "PHISHING_ATTACK",
    63: "SQL_INJECTION",
    59: "PRIVILEGE_ESCALATION",
    2: "FAILED_LOGIN"
}
