const TableData = [
  {
    key: '1',
    name: 'a',
    staffId: 2,
    username: 'gov_123',
    designation: 'MRD',
    mobileNo: '123454678990',
    parentUnitId: 'BEL',
    authorityOfControl: 'yes',
  },
  {
    key: '2',
    name: 'b',
    staffId: 42,
    username: 'gov_124',
    mobileNo: '123454678990',
    designation: 'MRS',
    authorityOfControl: 'yes',
  },
  {
    key: '3',
    name: 'c',
    staffId: 32,
    username: 'gov_125',
    mobileNo: '123454678990',
    designation: 'CRS',
    parentUnitId: 'BEL',
  },
  {
    key: '4',
    name: 'd',
    staffId: 32,
    username: 'gov_126',
    mobileNo: '123454678990',
    designation: 'ABS',
    parentUnitId: 'BEL',
  },
  {
    key: '5',
    name: 'e',
    staffId: 3,
    username: 'gov_126',
    mobileNo: '123454678990',
    designation: 'ZKD',
    authorityOfControl: 'yes',
  },
];
export default TableData;
